'use strict';

const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

let mod;
async function load() {
  if (!mod) {
    mod = await import(require('node:url').pathToFileURL(
      path.join(__dirname, '..', '..', 'scripts', 'survey.mjs')).href);
  }
  return mod;
}

function project(files) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'survey-'));
  for (const [rel, body] of Object.entries(files)) {
    const full = path.join(root, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, body);
  }
  return root;
}

test('code is grouped by directory, never by file', async () => {
  // Slicing the path blindly turned `scripts/survey.mjs` into its own
  // "directory", which makes the map useless on a flat project.
  const { survey } = await load();
  const root = project({
    'src/a.ts': 'x\n', 'src/b.ts': 'x\n', 'scripts/one.mjs': 'x\n',
  });
  const r = survey(root);
  const names = r.dirs.map(([d]) => d);
  assert.ok(names.includes('src'), 'src was not grouped: ' + names.join(', '));
  assert.ok(!names.some((n) => n.endsWith('.mjs') || n.endsWith('.ts')),
    'a file was reported as a directory: ' + names.join(', '));
});

test('dependencies and build output are excluded from the map', async () => {
  const { survey } = await load();
  const root = project({
    'src/a.ts': 'x\n',
    'node_modules/pkg/index.js': 'x\n',
    'dist/bundle.js': 'x\n',
    'vendor/lib.js': 'x\n',
  });
  const r = survey(root);
  assert.strictEqual(r.counts.code, 1,
    'the map counted dependencies or build output: ' + r.counts.code);
});

test('a project with no tests says so as a fact about risk', async () => {
  // Code not protected by tests cannot be changed safely. That is the central
  // fact about a brownfield change, not a detail to mention in passing.
  const { survey } = await load();
  const root = project({ 'src/a.ts': 'x\n', 'src/b.ts': 'x\n' });
  const r = survey(root);
  assert.strictEqual(r.counts.tests, 0);
  assert.ok(r.unknowns.some((u) => /nothing pins current behaviour/.test(u)),
    'an untested codebase did not report that nothing pins its behaviour');
});

test('tests are recognised by several conventions', async () => {
  const { survey } = await load();
  const root = project({
    'src/a.ts': 'x\n',
    'src/a.test.ts': 'x\n',
    'tests/b.py': 'x\n',
    '__tests__/c.js': 'x\n',
    'spec/d.rb': 'x\n',
  });
  const r = survey(root);
  assert.strictEqual(r.counts.tests, 4, 'missed a test convention: ' + r.counts.tests);
});

test('generated files are flagged so nobody hand-edits them', async () => {
  // Editing one is work that vanishes on the next build.
  const { survey } = await load();
  const root = project({
    'src/api.ts': '// @generated by openapi-codegen. DO NOT EDIT.\nexport const x = 1;\n',
    'src/mine.ts': 'export const y = 2;\n',
  });
  const r = survey(root);
  assert.deepStrictEqual(r.generated, ['src/api.ts']);
});

test('what the survey could not establish is reported, not omitted', async () => {
  // An unexplored area is an unknown, not an absence. A survey that omits its
  // blind spots reads as a clean bill.
  const { survey } = await load();
  const root = project({ 'src/a.ts': 'x\n' });
  const r = survey(root);
  assert.ok(r.unknowns.length, 'a project with no git, no manifest and no tests reported no unknowns');
  assert.ok(r.unknowns.some((u) => /not a git repository/.test(u)));
  assert.ok(r.unknowns.some((u) => /no dependency manifest/.test(u)));
});

test('no entry point found is an unknown, not silence', async () => {
  const { survey } = await load();
  const root = project({ 'src/helper.ts': 'x\n' });
  const r = survey(root);
  assert.deepStrictEqual(r.entries, []);
  assert.ok(r.unknowns.some((u) => /where execution starts is unknown/.test(u)),
    'an unrecognised entry point was reported as nothing at all');
});

test('entry points are recognised across stacks', async () => {
  const { survey } = await load();
  const root = project({
    'src/app/jobs/page.tsx': 'x\n',
    'manage.py': 'x\n',
    'cmd/main.go': 'x\n',
    'next.config.ts': 'x\n',
    'src/random.ts': 'x\n',
  });
  const r = survey(root);
  for (const expected of ['src/app/jobs/page.tsx', 'manage.py', 'cmd/main.go', 'next.config.ts']) {
    assert.ok(r.entries.includes(expected), 'missed entry point ' + expected);
  }
  assert.ok(!r.entries.includes('src/random.ts'));
});

test('a missing directory is reported rather than surveyed as empty', async () => {
  const { survey } = await load();
  const r = survey(path.join(os.tmpdir(), 'no-such-project-' + Date.now()));
  assert.strictEqual(r.ok, false);
  assert.match(r.error, /no such directory/);
});
