// Orientation for a codebase nobody on this team has seen before.
//
// Every test of this plugin was greenfield, and it shows: stack-profile opens
// with "Generate, do not author" -- run a scaffolder. On an existing project
// there is nothing to generate. There is something to discover, and an agent
// that discovers it by making fifty exploratory tool calls is slow, expensive,
// and produces conclusions nobody can check.
//
// This produces the map in one command: where the code is, what the
// conventions are, what is tested, where the churn is, and what must not be
// touched. Facts, cheaply, so the reading that follows can be aimed.
//
// Usage: node scripts/survey.mjs [root] [--json]

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const SKIP = new Set([
  'node_modules', '.git', '.next', '.nuxt', '.svelte-kit', '.astro', 'out',
  'dist', 'build', 'coverage', '.turbo', '.vercel', '.cache', '.venv',
  '__pycache__', 'vendor', 'third_party', '.devteam',
]);

const CODE_EXT = new Set([
  '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs', '.astro', '.vue', '.svelte',
  '.py', '.rb', '.go', '.rs', '.java', '.kt', '.php', '.cs', '.swift',
  '.css', '.scss', '.sass', '.less', '.sql', '.sh',
]);

const TEST = /(^|[./\\])(test|tests|spec|__tests__|e2e)([./\\]|$)|\.(test|spec)\.[a-z]+$/i;
const GENERATED = /@generated|DO NOT EDIT|Code generated by|auto-generated/i;

const ENTRY = [
  /(^|\/)(app|pages)\/.*\/(page|route|layout)\.[cm]?[jt]sx?$/,
  /(^|\/)(main|index|app|server|cli)\.[cm]?[jt]sx?$/,
  /(^|\/)__main__\.py$/, /(^|\/)manage\.py$/, /(^|\/)wsgi\.py$/, /(^|\/)asgi\.py$/,
  /(^|\/)main\.go$/, /(^|\/)main\.rs$/,
  /\.config\.[cm]?[jt]s$/, /(^|\/)Dockerfile$/, /(^|\/)Makefile$/,
];

const rel = (root, f) => path.relative(root, f).split(path.sep).join('/');

function walk(dir, out = [], depth = 0) {
  if (depth > 12) return out;
  let entries;
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return out; }
  for (const e of entries) {
    if (SKIP.has(e.name)) continue;
    if (e.name.startsWith('.') && e.name !== '.github') continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full, out, depth + 1);
    else out.push(full);
  }
  return out;
}

function git(root, args) {
  const r = spawnSync('git', args, { cwd: root, encoding: 'utf8' });
  return r.status === 0 ? String(r.stdout || '').trim() : null;
}

function topCounts(items, n) {
  const by = new Map();
  for (const i of items) by.set(i, (by.get(i) || 0) + 1);
  return [...by.entries()].sort((a, b) => b[1] - a[1]).slice(0, n);
}

export function survey(root) {
  if (!fs.existsSync(root)) return { ok: false, error: `no such directory: ${root}` };

  const files = walk(root).map((f) => rel(root, f));
  const code = files.filter((f) => CODE_EXT.has(path.extname(f)));
  const tests = code.filter((f) => TEST.test(f));
  const entries = files.filter((f) => ENTRY.some((re) => re.test(f)));

  // Directories carrying the most code, which is where the project actually is.
  // Group by the containing directory, never the file itself -- slicing the
  // path blindly turned `scripts/survey.mjs` into its own "directory".
  const dirs = topCounts(code.map((f) => {
    const parts = f.split('/');
    parts.pop();
    return parts.slice(0, 2).join('/') || '(root)';
  }), 8);
  const exts = topCounts(code.map((f) => path.extname(f)), 8);

  // Generated and vendored files must not be hand-edited. Sampled rather than
  // read whole -- the marker is conventionally in the first lines.
  const generated = [];
  for (const f of code.slice(0, 4000)) {
    try {
      const fd = fs.openSync(path.join(root, f), 'r');
      const buf = Buffer.alloc(400);
      const n = fs.readSync(fd, buf, 0, 400, 0);
      fs.closeSync(fd);
      if (GENERATED.test(buf.slice(0, n).toString('utf8'))) generated.push(f);
    } catch { /* unreadable, skip */ }
  }

  let manifest = null;
  for (const name of ['package.json', 'pyproject.toml', 'go.mod', 'Cargo.toml', 'Gemfile', 'composer.json']) {
    if (files.includes(name)) { manifest = name; break; }
  }
  let deps = [];
  if (manifest === 'package.json') {
    try {
      const p = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
      deps = Object.keys({ ...(p.dependencies || {}), ...(p.devDependencies || {}) });
    } catch { /* unparseable */ }
  }

  // Churn: where the work has actually been happening. A far better guide to
  // what matters than directory size.
  const isRepo = git(root, ['rev-parse', '--is-inside-work-tree']) === 'true';
  let churn = [], commits = null, firstCommit = null, lastCommit = null, contributors = null;
  if (isRepo) {
    const names = git(root, ['log', '--format=', '--name-only', '-n', '400']);
    if (names) {
      churn = topCounts(names.split('\n').map((s) => s.trim()).filter(Boolean)
        .filter((f) => CODE_EXT.has(path.extname(f))), 8);
    }
    commits = Number(git(root, ['rev-list', '--count', 'HEAD']) || 0) || null;
    firstCommit = git(root, ['log', '--reverse', '--format=%as', '--max-parents=0', '-n', '1']);
    lastCommit = git(root, ['log', '-1', '--format=%as']);
    const shortlog = git(root, ['shortlog', '-sn', '--all', '-n']);
    contributors = shortlog ? shortlog.split('\n').filter(Boolean).length : null;
  }

  // What this pass could not establish. An unexplored area is an unknown, not
  // an absence, and a survey that omits its own blind spots invites an agent
  // to treat silence as a clean bill.
  const unknowns = [];
  if (!isRepo) unknowns.push('not a git repository, so there is no history to learn from');
  if (!manifest) unknowns.push('no dependency manifest recognised, so the stack is unconfirmed');
  if (!tests.length) unknowns.push('no test files found, so nothing pins current behaviour');
  if (code.length > 4000) unknowns.push(`only the first 4000 of ${code.length} code files were scanned for generated markers`);
  if (!entries.length) unknowns.push('no entry points recognised, so where execution starts is unknown -- find it by reading before changing anything');

  return {
    ok: true,
    root,
    counts: { files: files.length, code: code.length, tests: tests.length },
    testRatio: code.length ? Math.round((tests.length / code.length) * 100) : 0,
    dirs, exts,
    entries: entries.slice(0, 12),
    generated: generated.slice(0, 8),
    generatedCount: generated.length,
    manifest, depCount: deps.length,
    history: { isRepo, commits, firstCommit, lastCommit, contributors },
    churn,
    unknowns,
  };
}

function report(r) {
  if (!r.ok) { console.error('survey: ' + r.error); return 2; }
  const out = [];
  const pct = (n, d) => (d ? Math.round((n / d) * 100) : 0);

  out.push(`${r.counts.code} code files (${r.counts.files} total, excluding dependencies and build output)`);
  if (r.history.isRepo) {
    out.push(`history: ${r.history.commits ?? '?'} commits` +
      (r.history.firstCommit ? `, ${r.history.firstCommit} to ${r.history.lastCommit}` : '') +
      (r.history.contributors ? `, ${r.history.contributors} contributor(s)` : ''));
  }

  out.push('', 'where the code is:');
  for (const [d, n] of r.dirs) out.push(`  ${String(n).padStart(5)}  ${d || '(root)'}  ${pct(n, r.counts.code)}%`);
  out.push('  by type: ' + r.exts.map(([e, n]) => `${e} ${n}`).join(', '));

  out.push('', `tests: ${r.counts.tests} files, ${r.testRatio}% of the code`);
  if (!r.counts.tests) out.push('  NOTHING pins current behaviour. Any change here is unprotected.');

  if (r.churn.length) {
    out.push('', 'where the work has been happening (last 400 commits):');
    for (const [f, n] of r.churn) out.push(`  ${String(n).padStart(4)}x  ${f}`);
    out.push('  Churn is a better guide to what matters than directory size.');
  }

  if (r.entries.length) {
    out.push('', 'entry points -- start reading here:');
    for (const e of r.entries) out.push(`  ${e}`);
  }

  if (r.generatedCount) {
    out.push('', `generated or vendored -- ${r.generatedCount}, do not hand-edit:`);
    for (const g of r.generated) out.push(`  ${g}`);
  }

  if (r.manifest) out.push('', `manifest: ${r.manifest}${r.depCount ? `, ${r.depCount} dependencies` : ''}`);

  if (r.unknowns.length) {
    out.push('', 'this survey could NOT establish:');
    for (const u of r.unknowns) out.push(`  - ${u}`);
    out.push('  Record these as unknowns. Silence here is not a clean bill.');
  }

  console.log(out.join('\n'));
  return 0;
}

const invokedDirectly = (() => {
  if (!process.argv[1]) return false;
  try { return import.meta.url.endsWith(path.basename(process.argv[1])); } catch { return false; }
})();

if (invokedDirectly) {
  const args = process.argv.slice(2);
  const root = path.resolve(args.find((a) => !a.startsWith('--')) || process.cwd());
  const r = survey(root);
  if (args.includes('--json')) { console.log(JSON.stringify(r, null, 2)); process.exit(r.ok ? 0 : 2); }
  process.exit(report(r));
}
